### ISSUE TITLE
Getting it to work with Factorio 1.0

### ISSUE THREAD

**Issue by veksen** [BlooperDB/factorio-render#16]
Hello! I'm wondering what would be the steps to get this working for Factorio 1.0? I could not get the assets working, as the schema seemed to have changed a bit.

Willing to PR and contribute if necessary, I just would like to know where/what is needed to get started.

**Comment by devmattrick** [comment]
This library never ended up being completed in a production ready state. A lot of the code will be useful to reference, but at this point its probably best to do a rewrite instead of adding 1.0 support. A good place to start is @Vilsol's [FactorioDataExtractor](https://github.com/Vilsol/FactorioDataExtractor), which scrapes the data directly from the Lua files and saves them into a more portable json format, although I imagine it would need updating to work on 1.0.

factorio-render and Blooper as a whole have been on hiatus for a while, so unless we end up deciding to pick this project back up again, its probably best to look elsewhere or make your own, but feel free to use the code in this repository as reference!
